manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      # Tested ZMK v0.3-compatible revision (upstream branch: zmk-0.3).
      revision: 5c5af40de4d8cdf55dc63c4c5907af1e52da6a95
      path: modules/pmw3610
  self:
    path: config
